### ISSUE TITLE
[1.21.1][Neoforge] Armor Voiding still buggy

### ISSUE THREAD

**Issue by ffuentesm** [Leclowndu93150/Corpse-Gravestone-Curios-Compat#6]
The Take All Function is a bit weird, as I seem to be receiving the armor that vanished from an earlier death. 
I checked and I had nothing in the cosmetic armor slot. This was the armor I was wearing normally when I died. 

Before I pick up
![image](https://github.com/user-attachments/assets/47beb23c-6cc8-44a7-8ac4-67d71930c53f)
After I pick up
![image](https://github.com/user-attachments/assets/2abcf15f-8ef0-44c7-b283-cbe0e02244e3)

**Comment by Leclowndu93150** [comment]
im gonna bang my head against the wall lmao
