### ISSUE TITLE
You can transfer items from the death history GUI

### ISSUE THREAD

**Issue by Zynax1** [Leclowndu93150/Corpse-Gravestone-Curios-Compat#7]
In the "additional items" section there is the transfer items button in the top right corner, which **should** be disabled in the death history GUI but isn't. This enables you to dupe curios items as you can take them from both your corpse and the death history GUI. See the attached video for proof, I have also tested without Corpse x Curios API Compat installed and the transfer items button is correctly disabled in the death history GUI. 

https://github.com/user-attachments/assets/a47d6191-263f-462c-99c8-79d8edd4aca8

**Comment by Leclowndu93150** [comment]
LMAO. I better rework this mod
